# Generated by Django 5.2.17 on 2026-08-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ประเภทชา')),
            ],
        ),
        migrations.CreateModel(
            name='TeaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อเมนูชา')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ราคา (บาท)')),
                ('stock', models.IntegerField(default=0, verbose_name='สต็อกคงเหลือ (แก้ว)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea_stock.category', verbose_name='ประเภท')),
            ],
        ),
    ]
