# Generated by Django 5.2.17 on 2026-08-25 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea_stock.category', verbose_name='ประเภท'),
        ),
    ]
