# Generated by Django 5.2.17 on 2026-08-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='ชื่อจริง')),
                ('last_name', models.CharField(max_length=50, verbose_name='นามสกุล')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='อีเมล')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('department', models.CharField(choices=[('HR', 'ทรัพยากรบุคคล'), ('IT', 'เทคโนโลยีสารสนเทศ'), ('Sales', 'ฝ่ายขาย'), ('Marketing', 'การตลาด')], max_length=50, verbose_name='แผนก')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='เงินเดือน')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/', verbose_name='รูปโปรไฟล์')),
            ],
        ),
    ]
