# Generated by Django 5.2.17 on 2026-08-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัสอุปกรณ์/บาร์โค้ด')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่ออุปกรณ์')),
                ('category', models.CharField(choices=[('cardio', 'เครื่องคาร์ดิโอ (Cardio)'), ('strength', 'เครื่องเวทเทรนนิ่ง (Strength)'), ('freeweight', 'ฟรีเวทและดัมเบล (Free Weights)'), ('accessories', 'อุปกรณ์เสริม/เซฟตี้ (Accessories)')], max_length=50, verbose_name='หมวดหมู่อุปกรณ์')),
                ('stock', models.IntegerField(default=1, verbose_name='จำนวนคงเหลือในคลัง')),
                ('location', models.CharField(default='โซนหลัก', max_length=100, verbose_name='สถานที่จัดเก็บ/โซน')),
                ('status', models.CharField(choices=[('available', 'พร้อมใช้งาน'), ('maintenance', 'ส่งซ่อม/บำรุง'), ('out_of_stock', 'สินค้าหมดสต็อก')], default='available', max_length=20, verbose_name='สถานะ')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ราคาต่อหน่วย (บาท)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
            ],
        ),
    ]
